name: TruffleHog Secrets Scan

on:
  workflow_dispatch:
    inputs:
      repo-url:
        required: true
        default: https://github.com/<repo>
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install TruffleHog
        run: |
          wget -q https://github.com/trufflesecurity/trufflehog/releases/download/v3.64.0/trufflehog_3.64.0_linux_amd64.tar.gz -O trufflehog.tar.gz
          sudo tar xzf trufflehog.tar.gz --directory=/usr/local/bin/ trufflehog

      - name: Scan for Unverified and Verified Keys
        run: |
          trufflehog git ${{ github.event.inputs.repo-url }} --json | tee all-keys.json
          trufflehog git ${{ github.event.inputs.repo-url }} --only-verified --json | tee verified-keys.json

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Convert JSON to Excel
        run: python convert_to_excel.py

      - name: Upload Excel File
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-results
          path: trufflehog-results.xlsx
